(**
 A dumb config in EBNF? Very simple but yeah
*)

character = ? any character except '"' ? | escape_sequence ;
escape_sequence = '\\' , ( '"' | '\\' | 'n' | 'r' | 'a' | character ) ;
stringbit = '"' , { character | escape_sequence } , '"' ;
string = stringbit;

pair = string, "=", string ;
comment = "#", ( string | pair ) ;

config = { 
    ( comment | ( pair, comment ) ), 
    ? newline ? 
} ;
