log_file = { log_entry } ;
log_entry = (timestamp, log_level, log_message, newline) ;
timestamp = ("[", date, time, "]") ;
date = (year, "_", month, "_", day) ;
date_separator = ( "_" | "-" | "/" | "|" ) ;
year = (digit, digit, digit, digit) ;
month = (digit, digit) ;
day = (digit, digit) ;
time = (hour, ":", minute, ":", second) ;
hour = (digit, digit) ;
minute = (digit, digit) ;
second = (digit, digit) ;
log_level = ("INFO" | "DEBUG" | "WARNING" | "ERROR" | "CRITICAL") ;
log_message = text ;
newline = ? A special sequence representing newline, including esoteric newline sequences ? ;
digit = ("0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9") ;
text = { any_character } ;
any_character = ? any character except control characters and newline ? ;
