(**
 MXPSQL Simple EBNF
 
 This EBNF Grammar contains slightly minimalistic quality of life extensions by MXPSQL. Basically my version of EBNF.
 It was first written in January 13, 2023.
 Licensed under the MIT License.

 MIT License
 
 Copyright (c) 2023 MXPSQL
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 
 
 
 Behaviour of symbols based of ISO/IEC 14977
  * repetition-symbol
  - except-symbol
  , concatenate-symbol
  | definition-separator-symbol
  = defining-symbol
  ; terminator-symbol
  . terminator-symbol
 
 
 
 
 Example:
 
   # A string defined in MXPSQL's EBNF
   char = "A" | "B" | "C" | "D" | "E" | "F" | "G"
          | "H" | "I" | "J" | "K" | "L" | "M" | "N"
          | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
          | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
          | "c" | "d" | "e" | "f" | "g" | "h" | "i"
          | "j" | "k" | "l" | "m" | "n" | "o" | "p"
          | "q" | "r" | "s" | "t" | "u" | "v" | "w"
          | "x" | "y" | "z" ; # EBNF style assignment
   digit := "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9" ; # Walrus style assignment
   @include "symbol.ebnf"; # Include the identifier "symbol" from the file "symbol.ebnf"
   string ::= [{ char | digit | symbol }] ; # BNF style assignment

*)


letter = ( "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ) ;
digit_excluding_zero = ( "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ) ;
digit = ( "0" | digit_excluding_zero ) ;
symbol = ( "[" | "]" | "{" | "}" | "(" | ")" | "<" | ">"
       | "'" | '"' | "=" | "|" | "." | "," | ";" ) ;
character = ( letter | digit | symbol | "_" ) ;
 
identifier = ( letter , { letter | digit | "_" } ) ;
terminal = ( ( "'" , character - "'" , { character - "'" } , "'"  )
         | ( '"' , character - '"' , { character - '"' } , '"' ) ) ;

number = ( digit_excluding_zero, { digit } ) ;
all_characters = ( ( ? all visible characters ? ) | character ) ;
string = { all_characters } ;
quoted_string = ( ( '"', string, '"' ) 
         | ( "'", string, "'" ) ) ;

(* EBNF comments *)
start_comment = "(*" ;
end_comment = "*)" ;
multiline_comment = ( start_comment, string, end_comment ) ;

(* The star of MXPSQL Simple EBNF, these extensions. * )
singleline_comment = "#", string ;
directivemarker = "@", string, ( " " | "   " ), { quoted_string } ; (* Example => @include "blah.ebnf", @randomdirective "a total joke.txt" *)
extensions = ( singleline_comment | directivemarker ) ;

(* Groupings *)
comment = ( multiline_comment | singleline_comment ) ;

lhs = identifier ;
rhs = ( identifier
     | terminal (* Terminal Character *)
     | ( "<", string, ">" ) (* Ranges *)
     | ( "~", string, "~") (* Regex *)
     | ( ( [ number ] , "$", [ number ], rhs ) - ( "$", rhs ) ) (* Listing *)
     | ( ( [ number ] , "*", [ number ], rhs ) - ( "*", rhs ) ) (* Repetition *)
     | ( number, "%%", rhs ) (* Specific listing *)
     | (( number , "%", rhs ) - ( number, "%%", rhs )) (* Specific repetition *)
     | ( "[" , rhs , "]" ) (* Optional *)
     | ( "{" , rhs , "}" ) (* Repetition *)
     | ( "(" , rhs , ")" ) (* Grouping *)
     | ( "?", string, "?" ) (* The special sequence *)
     | ( rhs , ( "|" | "/" ) , rhs ) (* Slightly more powerful with "/" *)
     | ( rhs , "," , rhs ) (* Concatenation *)
     | ( rhs, "+" ) (* More than once *)
     | ( rhs, "&", rhs ) (* AND operation (Only include the right hand side of this expression if available) *)
     | ( rhs, "-", rhs ) (* Exceptions (It excludes the right hand side of this expression) *)
     | ( rhs, "^", rhs ) (* TBA *) 
     ) ;

rule = ( lhs , ( "::=" | ":=" | "=" ) , rhs , ( ";" | "." ), [ comment ] ) ; (* Multiple assignment and comments *)
statement = ( extensions | rules ) ; (* one line, maybe *)
grammar = { ( comment | statement ) } ; (* Ultimate one: The grammar ruleset *)
